### PR TITLE
[WIP]Users are authenticated closes #14

### LINKED ISSUE #14: authenticated user

### PR DESCRIPTION
**Pull request by mariastenquist**
-added feature test for user login
-scenario one: user can view a login page
-scenario two: user can fill out login and create acct

### CODE REVIEW

**Comment by samlandfried** [comment]
Ready for review, @dannyradden @mariastenquist

**Comment by jk1dd** [comment]
@Carmer @bethsebian hi! wondering about best practice with our branches as they are - pull request #44 contains everything in this request - how is this situation best handled?

**Comment by Carmer** [comment]
@jk1dd - I apologize I did not respond sooner. I missed the email notification for this tag. I don't quite understand the question. Could you elaborate?

**Comment by jk1dd** [comment]
@Carmer no worries - we spoke to beth and got it all cleared up! basically a git workflow question

**Pull request merged**
